---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(leaps)
library(CodeClanData)

```

```{r}
cars <- read_csv("car_dekho_details.csv") %>% 
  select(-"name")

```


```{r}
library(glmulti)
glmulti_fit <- glmulti(
  log(selling_price) ~ ., 
  data = cars,
  level = 1, # 2 = include pairwise interactions, 1 = main effects only (main effect = no pairwise interactions)
  minsize = 0, # no min size of model
  maxsize = -1, # -1 = no max size of model
  marginality = TRUE, # marginality here means the same as 'strongly hierarchical' interactions, i.e. include pairwise interactions only if both predictors present in the model as main effects.
  method = "g", # the problem is too large for exhaustive search, so search using a genetic algorithm
  crit = bic, # criteria for model selection is BIC value (lower is better)
  plotty = FALSE, # don't plot models as function runs
  report = TRUE, # do produce reports as function runs
  confsetsize = 100, # return best 100 solutions
  fitfunction = lm # fit using the `lm` function
)
```






